### ISSUE TITLE
Importing Lyft

### ISSUE THREAD

**Issue by jonluca** [djchie/lyft-node#1]
```const Lyft = require('lyft-node')``` does not work, you have to do ```const Lyft = require('lyft-node').default;```

Not really an issue, it's just not explained in the documentation, and if someone isn't using your set up it might be difficult to figure out.

Thanks again for this wrapper!

**Comment by djchie** [comment]
Definitely an issue if the instructions aren't clear haha. Just made a fix for it so you won't have to be using `.default` anymore. I'll push out a new version of the package soon. Thanks for pointing it out!

**Comment by pisgo** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
boe112, @bowenli86, @ahjwen, @deepimpactmir, @vivarox, @Sambhav22, @RamesesLabs, @jimenezrick, @mentor36, @k175ch, @infinity7592, @zhenshub, @all3n, @tianxiao-ma, @feguedi, @learsu, @Dyskovsky, @monque, @kaiya, @albertov, @maxkokocom, @abitduck, @smitto, @sh06, @gabrielrtakeda, @acefed, @netromdk, @shenzhigang, @kenfox-fedco, @wesleytian, @gaelroue, @v0l, @SHagege, @leaofelipe, @JingChaoChao, @icepat, @temmings, @OnlyMyRailgun, @sk-guritech, @xmsqh, @plentybytes, @opz, @feixionglee, @antimech, @JulianSoto, @alexk111, @ivorpeles, @agurod42, @zhouqiang-cl, @gaspardipseanmeverett, @benniaoge, @xbc30, @fdesjardins, @mornlee, @arswt, @roadchimp, @striveh, @mariosubspace, @jpentland, @hubitor, @liuxiu20180512, @MynxGithub, @haoxiang47, @Darren-H, @pedronasser, @codyaverett, @YellowSharkMT, @ahmetgunes, @skyoo2003, @chiaitian, @rkrockstar, @outsideris, @shan8851, @gustavogamino, @Lone333, @DI-O, @dclaoshi, @Boss19931007, @amresh1495, @kennylbj, @oezhouyou, @djboris9, @wsygwg, @stasterg, @cyssxt, @bodysen, @senticrypt, @Satily, @greatislee, @KevinZheng001, @HashBasher, @ArgenisDLR, @dongpin, @naory, @losymear, @BreezeWu, @ahmedx2, @jsh1n, @LJM760993108
